version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  pytest:
    jobs:
      - pytest

jobs:
  pytest:
    docker:
      - image: cimg/python:3.8.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - vro-{{ checksum "hypertension/py-root/poetry.lock"}}
      - run:
          name: "sudo apt-add-repository canonical"
          command: 'sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"'
      - run:
          name: "sudo apt-get install wkhtmltopdf"
          command: "sudo apt-get install wkhtmltopdf"
      - run:
          name: "Unit Tests"
          command: "cd hypertension; make pytest.ci"
          no_output_timeout: 10s
      - save_cache:
          key: vro-{{ checksum "hypertension/py-root/poetry.lock"}}
          paths:
            - hypertension/py-root/.venv
