version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  pytest:
    jobs:
      - pytest

jobs:
  pytest:
    docker:
      - image: julialeague/vro-hypertension-wkhtmltopdf:0.0.5
    steps:
      - checkout
      - run:
          name: "Unit Tests"
          command: "cd hypertension; make pytest.ci"
          no_output_timeout: 10s
