swagger: '3.0'
info:
  description: API for DC7343 logical processing
  version: 1.0.2
  title: DCC7343 algorithms

paths:
  /calculate:
    post:
      summary: processes patient data
      operationId: DC7343
      description:
        Determines if patient has active pancreatic cancer and/or is being treated with procedures/medicines for pancreatic cancer
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: medical_data_fhir
        description: Processed FHIR data
        schema:
          MedicalData:
            type: object
            required:
              - icn
              - vasrd
              - date_of_claim
              - condition
              - observation
              - medication
              - procedure
            properties:
              icn:
                type: integer
                example: 25
              date_of_claim:
                type: string
                format: date-time
                example: '2016-10-29T09:12:33.001Z'
              vasrd:
                type: integer
                example: 7343
              condition:
                $ref: '#/definitions/condition'
              observation:
                $ref: '#/definitions/observation'
              medication:
                $ref: '#/definitions/medication'
              procedure:
                $ref: '#/definitions/procedure'
      responses:
        200:
          description: processing successful 
          content:
            application/json:
              schema:
                response:
                  properties:
                    rrd_eligible:
                      type: boolean
                      example: True
                    evidence:
                      type: object
        400:
          description: processing failed

definitions:

  condition:
    required:
    - code
    - status
    - onset_date
    properties:
      code:
        type: string
        example: 363419009
      status: 
        type: string
        example: "active"
      text:
        type: string
        example: "Malignant tumor of head of pancreas (disorder)"
      onset_date:
        format: date-time
        example: '2016-08-29T09:12:33.001Z'
      abatement_date:
        format: date-time
        example: '2016-09-29T09:12:33.001Z'
  observation:
    properties:
      code:
        type: string
        example: '8462-4'
      text: 
        type: string
        example: 'Diastolic Blood Pressure'
      value:
        type: number
        example: 74.06721091966372
      unit:
        type: string
        example: "mm[Hg]"
  medication:
    required:
    - text
    - status
    - code
    - authoredOn
    properties:
      text:
        type: string
        example: "5-fluorouracil"
      code:
        type: string
        example: 4492
      authoredOn:
        format: date-time
        example: "2013-05-21T23:19:33Z"
  procedure:
    required:
    - code
    - performed_date
    properties:
      code:
        type: string
        example: 174710004
      text:
        type: string
        example: "(Surgery - distal subtotal pancreatectomy)"
      performed_date:
        format: date-time
        example: "2013-08-17T23:19:33Z"
      last_update_date: 
        format: date-time
        example: "2013-08-17T23:19:33Z"
      status: 
        type: string
        example: "completed"


# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /jbregstone/dc7343/1.0.0
schemes:
 - https