AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  hypertension-decider

  App to take CDW medical data as input and decide on appropriate disability grade

Resources:
  HypertensionMainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref PdfGeneratorLayer

  PdfGeneratorLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: layer/.
      Description: PDF Generator library - wkhtmltopdf
      LayerName: pdf-generator-layer
    # Metadata:
    #   BuildMethod: makefile
  # PDFGeneratorLayer:
  #   Type: AWS::Lambda::LayerVersion
  #   Properties:
  #     ContentUri: wkhtmltopdf/
  #     CompatibleRuntimes:
  #       - python3.8
  #   Metadata:
  #     BuildMethod: python
